# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-13 17:26
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChampionDto',
            fields=[
                ('rankedPlayEnabled', models.BooleanField()),
                ('botEnabled', models.BooleanField()),
                ('botMmEnabled', models.BooleanField()),
                ('active', models.BooleanField()),
                ('freeToPlay', models.BooleanField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChampionMasteryDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chestGranted', models.BooleanField()),
                ('championLevel', django.contrib.postgres.fields.jsonb.JSONField()),
                ('championPoints', models.IntegerField()),
                ('championId', models.BigIntegerField()),
                ('playerId', models.BigIntegerField()),
                ('championPointsUntilNextLevel', models.BigIntegerField()),
                ('tokensEarned', models.IntegerField()),
                ('championPointsSinceLastLevel', models.BigIntegerField()),
                ('lastPlayTime', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaguePositionDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=200)),
                ('queueType', models.CharField(max_length=200)),
                ('hotStreak', models.BooleanField()),
                ('wins', models.IntegerField()),
                ('veteran', models.BooleanField()),
                ('losses', models.IntegerField()),
                ('freshBlood', models.BooleanField()),
                ('leagueId', models.CharField(max_length=200)),
                ('playerOrTeamName', models.CharField(max_length=200)),
                ('inactive', models.BooleanField()),
                ('playerOrTeamId', models.CharField(max_length=200)),
                ('leagueName', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=200)),
                ('leaguePoints', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('seasonId', models.IntegerField()),
                ('queueId', models.IntegerField()),
                ('gameId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('participantIdentities', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gameVersion', models.CharField(max_length=200)),
                ('platformId', models.CharField(max_length=200)),
                ('gameMode', models.CharField(max_length=200)),
                ('mapId', models.IntegerField()),
                ('gameType', models.CharField(max_length=200)),
                ('teams', django.contrib.postgres.fields.jsonb.JSONField()),
                ('participants', django.contrib.postgres.fields.jsonb.JSONField()),
                ('gameDuration', models.BigIntegerField()),
                ('gameCreation', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummonerDTO',
            fields=[
                ('profileIconId', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('summonerLevel', models.BigIntegerField()),
                ('revisionDate', models.BigIntegerField()),
                ('id', models.BigIntegerField()),
                ('accountId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('matchList', django.contrib.postgres.fields.jsonb.JSONField()),
                ('analysis', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
