# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 09:54
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaguePositionDTO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=200)),
                ('queueType', models.CharField(max_length=200)),
                ('hotStreak', models.BooleanField()),
                ('wins', models.IntegerField()),
                ('veteran', models.BooleanField()),
                ('losses', models.IntegerField()),
                ('freshBlood', models.BooleanField()),
                ('leagueId', models.CharField(max_length=200)),
                ('playerOrTeamName', models.CharField(max_length=200)),
                ('inactive', models.BooleanField()),
                ('playerOrTeamId', models.CharField(max_length=200)),
                ('leagueName', models.CharField(max_length=200)),
                ('tier', models.CharField(max_length=200)),
                ('leaguePoints', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='summonerdto',
            name='analysis',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summonerdto',
            name='matchList',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
