# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-20 20:02
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180320_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='championdto',
            name='active',
        ),
        migrations.RemoveField(
            model_name='championdto',
            name='botEnabled',
        ),
        migrations.RemoveField(
            model_name='championdto',
            name='botMmEnabled',
        ),
        migrations.RemoveField(
            model_name='championdto',
            name='freeToPlay',
        ),
        migrations.RemoveField(
            model_name='championdto',
            name='rankedPlayEnabled',
        ),
        migrations.AddField(
            model_name='championdto',
            name='gold',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championdto',
            name='kda',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championdto',
            name='name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championdto',
            name='played',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championdto',
            name='win',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='championmasterydto',
            name='region',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaguepositiondto',
            name='region',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summonerdto',
            name='region',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
